import { z } from 'zod'
import { PullRequestViewBoundsSchema } from './workbench.js'

/**
 * Contract for the change report attached to a task.
 *
 * The page is generated by an agent and lives in Quuu's data area. The renderer never names a
 * file: it asks for the task's report and is handed back where main decided to keep it, so a
 * screen cannot point the view at something nobody generated.
 */
export const ReportStatusSchema = z.union([z.literal('generating'), z.literal('ready'), z.literal('failed')])
export type ReportStatus = z.infer<typeof ReportStatusSchema>

export const TaskReportSchema = z.object({
  taskId: z.string(),
  status: ReportStatusSchema,
  /** The worktree the report describes. Compared with the review's head to spot a stale one. */
  revision: z.string(),
  /** The page to display. Stays on the last readable report while a new one is being written. */
  path: z.string(),
  /** The generator's own output, for when a report failed or reads wrong. */
  logPath: z.string(),
  error: z.string(),
  startedAt: z.string(),
  endedAt: z.union([z.string(), z.null()])
})
export type TaskReport = z.infer<typeof TaskReportSchema>

export const ProjectReportSchema = TaskReportSchema.omit({ taskId: true }).extend({
  projectId: z.string(),
  /** Earliest automatic retry after a pre-launch failure. Manual regeneration bypasses it. */
  retryAt: z.string().nullable().optional()
})
export type ProjectReport = z.infer<typeof ProjectReportSchema>

/**
 * A page a generation produced, kept after newer ones replaced it.
 *
 * The page is a file; the entry says where it is. The renderer names an entry by `id` to show
 * it, never by path, so it can only open what main recorded.
 */
export const ReportHistoryEntrySchema = z.object({
  id: z.string(),
  path: z.string(),
  /** The tree the page describes. */
  revision: z.string(),
  generatedAt: z.string(),
  /** Whether this is the page the report shows now. */
  current: z.boolean()
})
export type ReportHistoryEntry = z.infer<typeof ReportHistoryEntrySchema>

export const ProjectReportViewRequestSchema = z.object({
  projectId: z.string(),
  bounds: PullRequestViewBoundsSchema,
  /** An earlier page from the history. Absent shows the current one. */
  historyId: z.string().optional()
})

export const ReportViewRequestSchema = z.object({
  taskId: z.string(),
  bounds: PullRequestViewBoundsSchema,
  /** An earlier page from the history. Absent shows the current one. */
  historyId: z.string().optional()
})
export type ReportViewRequest = z.infer<typeof ReportViewRequestSchema>
